### ISSUE TITLE
Function `inet_to_bigint` does not exist

### ISSUE THREAD

**Issue by ljufa** [ip2location/docker-ip2location-postgresql#3]
I followed instructions from the readme file and got this error in last step

`ERROR: function inet_to_bigint(unknown) does not exist`

**Comment by ip2location-com** [comment]
Please use the following command while we release a fix.

`SELECT * FROM ip2location_database WHERE ('8.8.8.8' - '0.0.0.0'::inet) <= ip_to LIMIT 1;`
